version: '3.7'

networks:
  kong-net:
    name: kong-net
    driver: bridge

services:
  service_test1:
    build:
      context: ./services/service_test1
    container_name: service-test1
    ports:
      - 8082:8082